
networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/crebelo-/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/crebelo-/data/wordpress

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    image: mariadb:inception
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
      - ../secrets/db_password.txt:/run/secrets/db_password.txt:ro
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password.txt:ro
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password.txt
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password.txt

    networks:
      - inception
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    build: ./requirements/nginx
    image: nginx:inception
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
      - ../secrets/db_password.txt:/run/secrets/db_password.txt:ro
      - ../secrets/admin_password.txt:/run/secrets/admin_password.txt:ro
      - ../secrets/test_password.txt:/run/secrets/test_password.txt:ro
    environment:
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password.txt
      - WORDPRESS_ADMIN_PASSWORD_FILE=/run/secrets/admin_password.txt
      - WORDPRESS_TEST_PASSWORD_FILE=/run/secrets/test_password.txt
    depends_on:
      - mariadb
    networks:
      - inception

